//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1 "github.com/sivchari/utilconversion/_example/api/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*MyResource)(nil), (*v1.MyResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MyResource_To_v1_MyResource(a.(*MyResource), b.(*v1.MyResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.MyResource)(nil), (*MyResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MyResource_To_v1alpha1_MyResource(a.(*v1.MyResource), b.(*MyResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MyResourceStatus)(nil), (*v1.MyResourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MyResourceStatus_To_v1_MyResourceStatus(a.(*MyResourceStatus), b.(*v1.MyResourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.MyResourceStatus)(nil), (*MyResourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MyResourceStatus_To_v1alpha1_MyResourceStatus(a.(*v1.MyResourceStatus), b.(*MyResourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.MyResourceSpec)(nil), (*MyResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MyResourceSpec_To_v1alpha1_MyResourceSpec(a.(*v1.MyResourceSpec), b.(*MyResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*MyResourceSpec)(nil), (*v1.MyResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MyResourceSpec_To_v1_MyResourceSpec(a.(*MyResourceSpec), b.(*v1.MyResourceSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_MyResource_To_v1_MyResource(in *MyResource, out *v1.MyResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MyResourceSpec_To_v1_MyResourceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MyResourceStatus_To_v1_MyResourceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MyResource_To_v1_MyResource is an autogenerated conversion function.
func Convert_v1alpha1_MyResource_To_v1_MyResource(in *MyResource, out *v1.MyResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_MyResource_To_v1_MyResource(in, out, s)
}

func autoConvert_v1_MyResource_To_v1alpha1_MyResource(in *v1.MyResource, out *MyResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_MyResourceSpec_To_v1alpha1_MyResourceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_MyResourceStatus_To_v1alpha1_MyResourceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_MyResource_To_v1alpha1_MyResource is an autogenerated conversion function.
func Convert_v1_MyResource_To_v1alpha1_MyResource(in *v1.MyResource, out *MyResource, s conversion.Scope) error {
	return autoConvert_v1_MyResource_To_v1alpha1_MyResource(in, out, s)
}

func autoConvert_v1alpha1_MyResourceSpec_To_v1_MyResourceSpec(in *MyResourceSpec, out *v1.MyResourceSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Replicas = in.Replicas
	// WARNING: in.OldField requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1_MyResourceSpec_To_v1alpha1_MyResourceSpec(in *v1.MyResourceSpec, out *MyResourceSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Replicas = in.Replicas
	// WARNING: in.NewField requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_MyResourceStatus_To_v1_MyResourceStatus(in *MyResourceStatus, out *v1.MyResourceStatus, s conversion.Scope) error {
	if err := metav1.Convert_bool_To_Pointer_bool(&in.Ready, &out.Ready, s); err != nil {
		return err
	}
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_MyResourceStatus_To_v1_MyResourceStatus is an autogenerated conversion function.
func Convert_v1alpha1_MyResourceStatus_To_v1_MyResourceStatus(in *MyResourceStatus, out *v1.MyResourceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MyResourceStatus_To_v1_MyResourceStatus(in, out, s)
}

func autoConvert_v1_MyResourceStatus_To_v1alpha1_MyResourceStatus(in *v1.MyResourceStatus, out *MyResourceStatus, s conversion.Scope) error {
	if err := metav1.Convert_Pointer_bool_To_bool(&in.Ready, &out.Ready, s); err != nil {
		return err
	}
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1_MyResourceStatus_To_v1alpha1_MyResourceStatus is an autogenerated conversion function.
func Convert_v1_MyResourceStatus_To_v1alpha1_MyResourceStatus(in *v1.MyResourceStatus, out *MyResourceStatus, s conversion.Scope) error {
	return autoConvert_v1_MyResourceStatus_To_v1alpha1_MyResourceStatus(in, out, s)
}
